name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install cross compilation toolchain
              run: |
                  rustup target add aarch64-linux-android

            - name: Build
              run: cargo build --target aarch64-linux-android --release

            - name: Test
              run: cargo test -vv
